version: '3.8'
services:
  db:
    image: postgres:15
    container_name: legal_db
    restart: always
    environment:
      POSTGRES_USER: user_legal
      POSTGRES_PASSWORD: password_legal
      POSTGRES_DB: legal_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: